In [4]:
import torch
device = ""
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"  # macOS m1 的 mps ≈ NVIDIA 1050Ti
else:
    device = "cpu"
# 每次setting里更改本地或远程的解释器, 看这里是cuda还是mps就知道有没有切成功了
# 现在每次都得重新打开项目,才切换
print(f"Using {device} device")

Using cuda device


In [5]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x.shape, x.numel()  # num of elements

(torch.Size([12]), 12)

In [7]:
x.reshape(2, 3, -1)  # <=>2,3,2

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])

In [8]:
x.reshape(3, -1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
torch.zeros((2, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.ones(2)

tensor([1., 1.])

In [11]:
torch.randn((2, 3, 4))

tensor([[[ 1.2820, -0.7593, -0.6062, -0.9267],
         [-0.1872,  0.3729,  1.2597,  0.9664],
         [ 0.7288, -0.5261, -0.2300,  0.4441]],

        [[-0.9746, -1.0643, -0.6751, -0.1700],
         [ 0.4167, -1.3299, -0.2828,  1.8716],
         [ 0.9378,  0.5792,  0.9252, -0.0098]]])

In [12]:
# 可以手动赋值创建
x = torch.tensor([[1, 2, 3], [2, 0, 0.]])
x, x.shape, x.dtype

(tensor([[1., 2., 3.],
         [2., 0., 0.]]),
 torch.Size([2, 3]),
 torch.float32)

In [13]:
# 转类型
x.type(torch.int64), x.int()  # 两者等价

(tensor([[1, 2, 3],
         [2, 0, 0]]),
 tensor([[1, 2, 3],
         [2, 0, 0]], dtype=torch.int32))

In [14]:
x = torch.tensor([1.0, 2, 3, 4])
y = torch.tensor([4, 3, 3, 3])
x + y, x - y, x * y, x / y, x ** y  # **是幂运算

(tensor([5., 5., 6., 7.]),
 tensor([-3., -1.,  0.,  1.]),
 tensor([ 4.,  6.,  9., 12.]),
 tensor([0.2500, 0.6667, 1.0000, 1.3333]),
 tensor([ 1.,  8., 27., 64.]))

In [15]:
torch.exp(x)  # e的x次幂

tensor([ 2.7183,  7.3891, 20.0855, 54.5981])

In [16]:
# tensor连结
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor(([2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]))
X, Y, torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)
# dim=0 表示在行上拼接(增加行),dim=1 表示在列上拼接(增加列)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [17]:
# 通过逻辑运算符构建二元张量
X == Y, X > Y, X < Y

(tensor([[False,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [18]:
X.sum(), X.int(), Y.prod()  # 聚合函数, 生成单元素tensor

(tensor(66.),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]], dtype=torch.int32),
 tensor(13824.))

In [19]:
# 即使shape不同, 仍可通过广播机制(broadcast mechanism)按元素操作
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [20]:
a + b  # 维度一致,均扩成3x2,缺失的行列复制已有的

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [21]:
X, X[1, 2], X[-1], X[1:3]  # 元素查询,切片

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor(6.),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [22]:
# 元素赋值
X[0:2, :] = 666
X[1, 2] = 777
X

tensor([[666., 666., 666., 666.],
        [666., 666., 777., 666.],
        [  8.,   9.,  10.,  11.]])

In [23]:
# 一些操作会导致为新结果分配内存
before = id(Y)
Y = Y + X  # 如果用Y[:]=Y+X或者Y+=X , 则不会重新分配内存
id(Y) == before

False

In [24]:
# 执行原地操作
Z1 = torch.zeros_like(Y)
Z2 = torch.zeros_like(Y)
before1 = id(Z1)
before2 = id(Z2)
Z1[:] = Z1 + X
Z2 += X
id(Z1) == before1, id(Z2) == before2

(True, True)

In [25]:
# NumPy
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [26]:
# 将标量tensor转化为普通类型标量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)




其他:

In [27]:
import torch
a = torch.arange(12)
print(a)
b = a.reshape(3, 4)
b[:] = 2
print(a)  # 注意: a的值也被改变了

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
