### 向量

In [1]:
import torch

# 向量(1-d)
x = torch.tensor([3.0])
y = torch.tensor([2.0])
x + y, x * y, x / y, x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [2]:
# 注意,单值的向量与标量区分!!
x_0d = torch.tensor(3.0)  # 0-d tensor 这是一个标量
x_0d.shape, x.shape, x_0d.shape == x.shape, x_0d == x

(torch.Size([]), torch.Size([1]), False, tensor([True]))

In [3]:
# torch.arange() Returns a 1-D tensor
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [4]:
x[3], x[3].shape  # 通过索引访问,1-d向量的元素是一个标量

(tensor(3), torch.Size([]))

In [5]:
len(x), x.shape
# 注意,如果x=torch.tensor(3.0), 就会报错:TypeError: len() of a 0-d tensor

(4, torch.Size([4]))

---
### 矩阵

In [6]:
# 矩阵
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [7]:
A.T  # 转置

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [8]:
X = torch.arange(24).reshape(2, 3, 4)  # 3-d tensor 3个轴
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [9]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存创建一个张量
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [10]:
# 矩阵按元素乘法
A * B, (A * B).shape

(tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]]),
 torch.Size([5, 4]))

↑ 哈达玛积(Hadamard product) (i.e.点乘, 数学符号: $\odot$)

In [11]:
# 数乘
2 * A, (2 * A).shape

(tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]),
 torch.Size([5, 4]))

In [12]:
# 元素的和 (=所有标量元素的和, 不论shape)
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [13]:
# 指定轴求和
C = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)
C_sum_axis0 = C.sum(axis=0)
C, C_sum_axis0, C_sum_axis0.shape

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 tensor([[12., 14., 16., 18.],
         [20., 22., 24., 26.],
         [28., 30., 32., 34.]]),
 torch.Size([3, 4]))

In [14]:
C_sum_axis1 = C.sum(axis=1)
C, C_sum_axis1, C_sum_axis1.shape

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 tensor([[12., 15., 18., 21.],
         [48., 51., 54., 57.]]),
 torch.Size([2, 4]))

In [15]:
C_sum_axis2 = C.sum(axis=2)
C, C_sum_axis2, C_sum_axis2.shape

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 tensor([[ 6., 22., 38.],
         [54., 70., 86.]]),
 torch.Size([2, 3]))

In [16]:
# 均值, 压缩某个轴的均值
C.mean(), C.mean(axis=0), C.mean(axis=0).shape

(tensor(11.5000),
 tensor([[ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.],
         [14., 15., 16., 17.]]),
 torch.Size([3, 4]))

In [17]:
# 计算聚合时,保持轴数不变
sum_C = C.sum(axis=0, keepdims=True)  # d-0不丢掉,但是只有1组
C, C_sum_axis0, C_sum_axis0.shape, sum_C, sum_C.shape
# 这里对比一下保留与不保留

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 tensor([[12., 14., 16., 18.],
         [20., 22., 24., 26.],
         [28., 30., 32., 34.]]),
 torch.Size([3, 4]),
 tensor([[[12., 14., 16., 18.],
          [20., 22., 24., 26.],
          [28., 30., 32., 34.]]]),
 torch.Size([1, 3, 4]))

In [18]:
# 然后可以利用广播机制, C/sum_C
C / sum_C  # 维度数必须相同, 某一个维度的size不同就会自动"广播"复制

tensor([[[0.0000, 0.0714, 0.1250, 0.1667],
         [0.2000, 0.2273, 0.2500, 0.2692],
         [0.2857, 0.3000, 0.3125, 0.3235]],

        [[1.0000, 0.9286, 0.8750, 0.8333],
         [0.8000, 0.7727, 0.7500, 0.7308],
         [0.7143, 0.7000, 0.6875, 0.6765]]])

In [19]:
# 累加求和
C, C.cumsum(axis=0)

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 14., 16., 18.],
          [20., 22., 24., 26.],
          [28., 30., 32., 34.]]]))

In [20]:
# 点积 = 按元素乘积的和
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
x, y, x * y, torch.dot(x, y), (x * y).sum()
# torch.dot(x,y)<=>(x*y).sum()

(tensor([0., 1., 2., 3.]),
 tensor([1., 1., 1., 1.]),
 tensor([0., 1., 2., 3.]),
 tensor(6.),
 tensor(6.))

In [21]:
# 矩阵*向量 => 一个列向量
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [22]:
# 矩阵乘法 (matrix multiplication)
# 可以看作是多次的 矩阵*向量, 然后将各个结果(列向量)拼接在一起
B = torch.ones(4, 3)
A, torch.mm(A, B)  # (5,4)*(4,3) => (5,3)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

---
### 范数
$$
\begin{flalign*}
&L_0范数 = 非零元素的个数&\\
&L_p范数 = \sqrt[p]{\sum |x_i|^p}\\
&L_{无穷} = 最大元素的绝对值\\
\end{flalign*}
$$

In [23]:
u = torch.arange(12, dtype=torch.float32).reshape(2, 2, 3)
l0 = u.norm(p=0)  # L0范数 = 非零元素的个数
l1 = u.norm(p=1)
l2 = u.norm(p=2)
l3 = u.norm(p=3)
l4 = u.norm(p=4)
l5 = u.norm(p=5)
l6 = u.norm(p=6)
l7 = u.norm(p=7)
l8 = u.norm(p=8)
l9 = u.norm(p=9)
l10 = u.norm(p=10)
l11 = u.norm(p=11)
l12 = u.norm(p=12)
l13 = u.norm(p=13)
l14 = u.norm(p=14)
l15 = u.norm(p=15)
l16 = u.norm(p=16)
l17 = u.norm(p=17)
l18 = u.norm(p=18)
l19 = u.norm(p=19)
l20 = u.norm(p=20)  # -> abs(u).max()
u, l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16, l17, l18, l19, l20, u.norm()
# norm()默认p=2, L2范数就是最常用的,i.e.F范数(Frobenius norm)

(tensor([[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.]],
 
         [[ 6.,  7.,  8.],
          [ 9., 10., 11.]]]),
 tensor(11.),
 tensor(66.),
 tensor(22.4944),
 tensor(16.3316),
 tensor(14.1398),
 tensor(13.0733),
 tensor(12.4644),
 tensor(12.0814),
 tensor(11.8242),
 tensor(11.6432),
 tensor(11.5112),
 tensor(11.4123),
 tensor(11.3366),
 tensor(11.2775),
 tensor(11.2307),
 tensor(11.1932),
 tensor(11.1627),
 tensor(11.1378),
 tensor(11.1173),
 tensor(11.1003),
 tensor(11.0860),
 tensor(22.4944))