### 读写文件

In [1]:
import torch
from torch import nn
from torch.nn import functional as F

# 加载和保存张量
x = torch.arange(4)
torch.save(x, 'x-file')

x2 = torch.load("x-file", weights_only=True)
x2

tensor([0, 1, 2, 3])

In [2]:
# tensor列表的rw
y = torch.zeros(4)
torch.save([x, y], 'x-files')
x2, y2 = torch.load('x-files', weights_only=True)
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [3]:
# tensor字典的rw
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict', weights_only=True)
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [4]:
# 模型参数的rw
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))


net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)
torch.save(net.state_dict(), 'mlp.params')
# load时需要实例化原始MLP的一个备份,然后用这个实例去装载load的内容
net_cp = MLP()
net_cp.load_state_dict(torch.load("mlp.params", weights_only=True))
net.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [5]:
Y_2 = net_cp(X)
Y_2 == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])